version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./tmp/redis:/data

  app:
    build: .
    volumes:
      - .:/usr/src/app
    tmpfs:
      - /usr/src/app/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    env_file:
      - .env